name: Treinamento GH Actions - Triggers

on:
 push:
  branches: 
   - master
 workflow_dispatch:

env:
 CAMINHO_PROJETO: ./SiteContagem/SiteContagem.csproj 

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: "Faz Checkout do Código Fonte"
    - uses: actions/checkout@v2
    
    - name: "Instala o SDK do .NET Core 3.1 no Runner"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build do Projeto
      run: dotnet build ${{ env.CAMINHO_PROJETO }} --configuration Release                     
 
 deploy-dev:
   if: github.ref == 'refs/heads/developer'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '                    
 deploy-prod:
   if: github.ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '              
