name: Treinamento GH Actions - Triggers

on:
 push:
  branches: 
   - master
 workflow_dispatch:

env:
 CAMINHO_PROJETO: ./SiteContagem/SiteContagem.csproj 
 CAMINHO_PUBLISH: app 

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: "Faz Checkout do Código Fonte"
      uses: actions/checkout@v2
    
    - name: "Instala o SDK do .NET Core 3.1 no Runner"
      uses: actions/setup-dotnet@v1
    
    - name: Build do Projeto
      run: dotnet publish ${{ env.CAMINHO_PROJETO }} -c Release -o ${{ env.CAMINHO_PUBLISH }}
      
    - name: Upload da Publicação como Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: APIContagem
        path: ${{ env.CAMINHO_PUBLISH }}     
 
 deploy-dev:
   if: github.ref == 'refs/heads/developer'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '                    
 deploy-prod:
   if: github.ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '              
